// lib/lib-quote.js -- LIB_QUOTE_V1: «انقل لي من كتاب …», answered with the book's own words.
//
// THE OWNER'S ASK (sources order, 24 September 2026). A reader who asks for the TEXT of a book --
// «ما نصّ كلام ابن قدامة في المغني عن المسح على الجوربين»، «انقل لي من كتاب زاد المعاد ما جاء في
// صلاة الضحى» -- is asking for a quotation, and a model's paraphrase of a quotation is exactly the
// thing that must never be presented as one. So the reply is composed HERE, by the server, from
// the library atom itself: a card line naming the book, its author and its place, then the atom's
// text letter for letter as a blockquote. No model call.
//
// WHAT THIS MODULE IS. Pure: it reads no environment and opens no socket. The library call is made
// through the `runTool` it is HANDED (lib/free-brain/tools.js -> runLibrary, the only door
// guards/lib-book-contract-guard.cjs row A7 allows), with the two library switches api/ask.js read.
// Book titles and authors are resolved OFFLINE against lib/data/lib-catalog.js (7,400 books,
// generated by tools/gen-lib-catalog.mjs) -- the service has no catalogue door, and its author door
// "corrects" names into other people (measured: القرضاوي -> القرعاوي), so it is never used here.
//
// WHAT IT CANNOT DO, AND SAYS SO. The service has no page door (only /search; decision D7 of the
// sources round), so «نص صفحة ٥٠ من الجزء ٢٥ من كتاب …» is answered honestly: no page by number,
// here is the road that works (name the topic). No page number is ever invented, and no reply
// names the machinery («المكتبة»، «الفهرس»، «الشاملة» …).
//
// WHY IT HAS ITS OWN WRITER. The finalizer and the takhrij seal were built for MODEL prose. On a
// real atom of عمدة القاري they read «روى ابن أبي شيبة …» inside the book's own text as an
// unsupported attribution and replaced the whole quotation with the refusal sentence (measured,
// 02-build/c3/finalizer-why.mjs). A quotation is not a draft to be repaired: it is either the
// book's text or it is not sent. `writeQuoteReply` writes the same two frames sendSynthesizedText
// writes, without that pass.
import { LIB_CATALOG } from './data/lib-catalog.js';
import { LIB_MAX_CHARS_PER_HIT_CEILING } from './lib-contract.js';
// م٤-د (LIB_NAV_V1) — «ل» on a name as Arabic writes it («للقرضاوي»، «لسيد قطب»، «لابن تيمية»).
import { withLam } from './arabic-lam.js';

// Positions in a catalogue row (tools/gen-lib-catalog.mjs writes them).
const ROW_ID = 0;
const ROW_TITLE = 1;
const ROW_AUTHOR = 2;
const ROW_CLS = 3;
const ROW_AUTO = 4;
const ROW_BLOCKED = 5;

/** Rows asked of the library for one quotation (the top one is quoted). */
export const QUOTE_ROWS = 3;
/** The quote path asks for the service's whole ceiling per atom, so fewer quotations arrive cut. */
export const QUOTE_MAX_CHARS = LIB_MAX_CHARS_PER_HIT_CEILING;
/** A modern book is quoted one paragraph, cut at a sentence end before this many characters. */
export const MODERN_QUOTE_MAX = 700;
/** How many books an «which one?» reply lists before it says there are more. */
export const ASK_LIST_MAX = 8;
/** The longest heading a card carries on an automatically numbered book. */
export const HEADING_MAX = 160;

const CUT_MARK = ' …';
const BOOK_MARK = '\u{1F4D6}';
const SEP = ' · ';

// ── FOLDING ─────────────────────────────────────────────────────────────────────
// Tashkeel, tatweel, the hamza seats, ta marbuta, alif maqsura, Arabic-Indic digits, and every
// non-letter to one space. Used to MATCH only: nothing a reader is shown is ever folded.
const TASHKEEL_RE = /[ؐ-ًؚ-ٰٟۖ-ۜ۟-۪ۨ-ۭ]/g;

export function foldArabic(value) {
  return String(value == null ? '' : value)
    .replace(TASHKEEL_RE, '')
    .replace(/ـ/g, '')
    .replace(/[آأإٱ-ٳ]/g, 'ا')
    .replace(/ؤ/g, 'و')
    .replace(/ئ/g, 'ي')
    .replace(/ة/g, 'ه')
    .replace(/[ىی]/g, 'ي')
    .replace(/[٠-٩]/g, (d) => String(d.charCodeAt(0) - 0x0660))
    .replace(/[۰-۹]/g, (d) => String(d.charCodeAt(0) - 0x06F0))
    .toLowerCase()
    .replace(/[^ء-غف-ي0-9a-z]+/g, ' ')
    .trim();
}

/** A title as the catalogue is matched on: folded, and without a leading «كتاب». */
export function normalizeTitle(title) {
  const folded = foldArabic(title);
  const bare = folded.replace(/^(?:ال)?كتاب /, '');
  return bare || folded;
}

const stripAl = (w) => (w.length > 3 && w.startsWith('ال') ? w.slice(2) : w);
// «ابن» and «بن» are one word to an author match («ابن عثيمين» / «محمد بن صالح العثيمين»).
const nameWord = (w) => (w === 'ابن' ? 'بن' : w);

// ── THE CATALOGUE ───────────────────────────────────────────────────────────────
let INDEX = null;
function catalogIndex() {
  if (INDEX) return INDEX;
  INDEX = LIB_CATALOG.map((row) => {
    const title = String(row[ROW_TITLE] || '');
    const alts = [];
    for (const t of [title, ...title.split('=')]) {
      const n = normalizeTitle(t);
      if (n && !alts.includes(n)) alts.push(n);
    }
    const hay = new Set();
    const put = (w) => { hay.add(nameWord(w)); hay.add(stripAl(w)); };
    for (const w of `${foldArabic(row[ROW_AUTHOR])} ${foldArabic(title)}`.split(' ')) {
      if (!w) continue;
      put(w);
      // «لابن قدامة» / «للعثيمين» in a title name the author with the preposition glued on.
      if (w.startsWith('لل') && w.length > 3) { put('ال' + w.slice(2)); put(w.slice(2)); }
      else if (w.startsWith('لا') && w.length > 3) put('ا' + w.slice(2));
    }
    return { row, alts, altWords: alts.map((a) => a.split(' ')), hay };
  });
  return INDEX;
}

function bookOf(row) {
  return Object.freeze({
    id: row[ROW_ID], title: row[ROW_TITLE], author: row[ROW_AUTHOR], cls: row[ROW_CLS],
    auto: row[ROW_AUTO] === 1, blocked: row[ROW_BLOCKED] === 1,
  });
}

/** The catalogue row for one library id, or null. */
export function catalogBook(id) {
  const hit = catalogIndex().find((e) => e.row[ROW_ID] === id);
  return hit ? bookOf(hit.row) : null;
}

const HONORIFIC_PHRASES = ['شيخ الاسلام', 'رحمه الله تعالي', 'رحمه الله', 'رحمهم الله', 'رضي الله عنه',
  'رضي الله عنهما', 'حفظه الله', 'سماحه الشيخ', 'فضيله الشيخ'];
const HONORIFIC_WORDS = new Set(['الامام', 'الشيخ', 'العلامه', 'الحافظ', 'الفقيه', 'المحدث', 'المفسر',
  'الدكتور', 'القاضي', 'تعالي', 'سماحه', 'فضيله']);

/** The words an author is matched on, with honorifics removed. */
export function authorKey(author) {
  let a = ` ${foldArabic(author)} `;
  for (const p of HONORIFIC_PHRASES) a = a.split(` ${p} `).join(' ');
  return a.split(' ').filter((w) => w && !HONORIFIC_WORDS.has(w));
}

function authorMatches(entry, words) {
  return words.every((w) => entry.hay.has(nameWord(w)) || entry.hay.has(stripAl(w)));
}

// «فتاويه» -- the reader named the author and the KIND of book, not a title (key decision QD5):
// every fatwa book of that author is one search scope.
const AUTHOR_SCOPE_TITLES = new Set(['فتاويه', 'فتاواه', 'فتاوي', 'الفتاوي', 'فتاويه ورسائله', 'مجموع فتاويه']);

/**
 * Title (+ author) -> catalogue books. `tier`: 3 exact, 2 prefix, 1 all words contained, 0 none.
 * A named author narrows the books; if it matches none of them, only an EXACT title survives
 * (name forms differ: «ابن قدامة» is «المقدسي، موفق الدين» in the catalogue) -- a looser title
 * under the wrong author is somebody else's book, so it resolves to nothing.
 */
export function resolveBook(title, author = '') {
  const want = normalizeTitle(title);
  const none = { tier: 0, books: [], authorMatched: false, authorScope: false };
  if (!want) return none;
  const key = authorKey(author);
  const index = catalogIndex();
  if (AUTHOR_SCOPE_TITLES.has(want) && key.length) {
    // His books of the fatwa class first; a titled «فتاوى …» of his only when he has none.
    const his = index.filter((e) => authorMatches(e, key));
    const fatwaClass = his.filter((e) => e.row[ROW_CLS] === 'fatwa');
    const own = fatwaClass.length ? fatwaClass : his.filter((e) => e.alts.some((a) => a.split(' ').includes('فتاوي')));
    return own.length
      ? { tier: 2, books: own.map((e) => bookOf(e.row)), authorMatched: true, authorScope: true }
      : none;
  }
  const words = want.split(' ');
  let tier = 0;
  let hits = index.filter((e) => e.alts.includes(want));
  if (hits.length) tier = 3;
  else {
    hits = index.filter((e) => e.alts.some((a) => a.startsWith(want + ' ')));
    if (hits.length) tier = 2;
    else {
      hits = index.filter((e) => e.altWords.some((ws) => words.every((w) => ws.includes(w))));
      if (hits.length) tier = 1;
    }
  }
  if (!hits.length) return none;
  let authorMatched = false;
  if (key.length) {
    const narrowed = hits.filter((e) => authorMatches(e, key));
    if (narrowed.length) { hits = narrowed; authorMatched = true; }
    else if (tier < 3) return none;
  }
  return { tier, books: hits.map((e) => bookOf(e.row)), authorMatched, authorScope: false };
}

// ── DETECTION ───────────────────────────────────────────────────────────────────
// Everything is matched on the FOLDED words of the reader's last message, and every span is kept
// as offsets into the original text, so the topic sent to the library is the reader's own words.
function wordsOf(text) {
  const src = String(text == null ? '' : text);
  const words = [];
  const re = /\S+/g;
  let m;
  while ((m = re.exec(src))) {
    const folded = foldArabic(m[0]);
    if (!folded) continue;
    for (const w of folded.split(' ')) words.push({ w, start: m.index, end: m.index + m[0].length });
  }
  const starts = [];
  let joined = '';
  for (const item of words) {
    if (joined) joined += ' ';
    starts.push(joined.length);
    joined += item.w;
  }
  return { src, words, joined, starts };
}

// Offset in the joined folded text -> index of the word that starts there (or the next one).
const wordIndexAt = (starts, offset) => {
  const i = starts.indexOf(offset);
  if (i !== -1) return i;
  const next = starts.findIndex((s) => s > offset);
  return next === -1 ? starts.length : next;
};

function span(src, ws) {
  if (!ws.length) return '';
  return src.slice(ws[0].start, ws[ws.length - 1].end)
    .replace(/^[\s«»"'()[\]{}:،,.؟?!؛;-]+|[\s«»"'()[\]{}:،,.؟?!؛;-]+$/gu, '').trim();
}

// A reader's request to be handed text, anywhere in the message (the «ماذا قال …» shape needs one).
const TEXT_CUE = /(?:^| )(?:نص|نصه|نصها|النص|بنصه|بالنص|انقل|انقله|انقلها|انسخ|انسخه|بحروفه|حرفيا|بالحرف)(?= |$)/;

// The shapes. `kitab` present = the reader named a BOOK in so many words ("explicit").
const KITAB = '(?:كتابه|كتاب|الكتاب)';
const VERB = '(?:انقل|انقلي|انقلوا|انسخ|اقتبس|اكتب|اقرا|هات|اعطني|اعطيني|اذكر|اورد)';
const SHAPES = [
  // (a1) «ما نصّ كلام <author> في كتابه <title> عن <topic>» / «نص فتوى <author> في <title> عن …»
  { name: 'kalam', re: new RegExp(`(?:^| )(?:نص|بنص|النص) (?:كلام|فتوي|قول|جواب|اجابه) (?<author>.+?) في (?<kitab>${KITAB} )?(?<rest>.+)$`, 'd') },
  // (a3) «اكتب لي نص ما قاله فلان في <title> عن …»
  { name: 'qalahu', re: new RegExp(`(?:^| )(?:نص|بنص|النص) (?:ما|الذي) (?:قاله|قال|ذكره|كتبه|قرره|سطره) (?<author>.+?) في (?<kitab>${KITAB} )?(?<rest>.+)$`, 'd') },
  // «ماذا قال الشيخ ابن باز في فتاويه عن …؟ اكتب لي نصه» -- only with a text cue in the message
  { name: 'qala', cue: true, re: new RegExp(`(?:^| )(?:ماذا|ما) (?:الذي )?(?:قال|قاله|ذكر|ذكره|كتب|كتبه|قرر|يقول) (?<author>.+?) في (?<kitab>${KITAB} )?(?<rest>.+)$`, 'd') },
  // «انقل لي نص ما جاء في كتاب <title> عن …»
  { name: 'jaa', re: new RegExp(`(?:^| )(?:نص|بنص|النص) ما (?:جاء|ورد|قيل|ذكر) في (?<kitab>${KITAB} )(?<rest>.+)$`, 'd') },
  // «انقل لي بالنص ما في <title> عن …»
  { name: 'bima', re: new RegExp(`(?:^| )${VERB}(?: لي| لنا)?(?: بالنص| نص| النص| حرفيا)? (?:ما|الذي) (?:جاء |ورد |قيل |ذكر )?في (?<kitab>${KITAB} )?(?<rest>.+)$`, 'd') },
  // (a2) «انقل لي من كتاب <title> ما جاء في <topic>»
  { name: 'minKitab', re: new RegExp(`(?:^| )${VERB}(?: لي| لنا)?(?: بالنص| نص| النص)? (?:من|في) (?<kitab>${KITAB} )(?<rest>.+)$`, 'd') },
  // «انقل لي من <title> ما جاء في …» -- no «كتاب», so it is taken only on a strong match (Q6)
  { name: 'min', re: /(?:^| )(?:انقل|انقلي|انقلوا|انسخ|اقتبس)(?: لي| لنا)?(?: بالنص| نص| النص)? من (?<rest>.+)$/d },
];

// Where the title ends and the topic begins: [«نص»] [«كلامه» | «ما جاء» …] («في» | «عن» | …).
// Longest first, so at one position «نص ما قيل عن» wins over «عن».
const MARKERS = (() => {
  const heads = [[], ['نص'], ['بالنص'], ['النص'], ['بنص']];
  const mids = [[], ['كلامه'], ['قوله'], ['ما', 'قيل'], ['ما', 'جاء'], ['ما', 'ورد'], ['ما', 'ذكر'],
    ['ما', 'ذكره'], ['ما', 'قاله'], ['ما', 'كتبه'], ['ما', 'قرره']];
  const tails = [['في'], ['عن'], ['حول'], ['بخصوص'], ['بشان'], ['في', 'باب'], ['في', 'مساله'],
    ['في', 'موضوع'], ['في', 'مسائل'], ['في', 'فصل'], ['فيما', 'يخص'], ['في', 'ما', 'يخص']];
  const out = [['باب'], ['من', 'باب']];
  for (const h of heads) for (const m of mids) for (const t of tails) out.push([...h, ...m, ...t]);
  return out.sort((a, b) => b.length - a.length);
})();
const TOPIC_LEAD = new Set(['باب', 'فصل', 'مساله', 'موضوع', 'مسائل']);
// A request tail after the topic («… انقله لي بحروفه»، «… ثم لخّصه لي») is not the topic.
const TOPIC_STOP = new Set(['انقله', 'انقلها', 'انقلوه', 'اكتبه', 'اكتبها', 'اكتب', 'انسخه', 'انسخها',
  'لخصه', 'لخصها', 'ولخصه', 'اشرحه', 'واشرحه', 'وضحه', 'بحروفه', 'بنصه', 'بالنص', 'حرفيا']);
const TRAILERS = [
  ['من', 'فضلك'], ['لو', 'سمحت'], ['بارك', 'الله', 'فيك'], ['جزاك', 'الله', 'خيرا'], ['بارك', 'الله', 'فيكم'],
  ['بالنص'], ['بنصه'], ['بالحرف'], ['حرفيا'], ['بحروفه'], ['كاملا'], ['كامل'], ['رجاء'], ['ثم'], ['لي'],
];
// «كتاب الله» is the Qur'an, not a book on a shelf.
const NOT_A_BOOK_FIRST = new Set(['الله', 'رب', 'ربنا', 'ربي', 'ربك', 'ربكم', 'الرحمن']);
const NOT_A_BOOK = new Set(['القران', 'القران الكريم', 'المصحف', 'المصحف الشريف']);
const AUTHOR_GLUE = /^(?:لل|لا)/;
const CLAUSE_END = /[؟?!.،,؛;]$/u;

function trimTrailers(ws) {
  let out = ws.slice();
  for (let changed = true; changed && out.length;) {
    changed = false;
    for (const t of TRAILERS) {
      if (out.length > t.length && t.every((w, i) => out[out.length - t.length + i].w === w)) {
        out = out.slice(0, out.length - t.length); changed = true;
      }
    }
  }
  return out;
}

function topicWords(src, ws) {
  let topic = ws.slice();
  // The topic ends at its clause: «… عن المسح على الجوربين؟ انقله لي بحروفه».
  const clause = topic.findIndex((x) => CLAUSE_END.test(src.slice(x.start, x.end)));
  if (clause !== -1) topic = topic.slice(0, clause + 1);
  const stop = topic.findIndex((x, i) => i > 0 && TOPIC_STOP.has(x.w));
  if (stop !== -1) topic = topic.slice(0, stop);
  topic = trimTrailers(topic);
  while (topic.length > 1 && TOPIC_LEAD.has(topic[0].w)) topic = topic.slice(1);
  return topic;
}

// One title reading, plus the reading with an author glued to its tail («زاد المعاد لابن القيم»).
function readings(src, titleWs, topic, author, authorText, strong) {
  const title = trimTrailers(titleWs);
  if (!title.length) return [];
  const out = [{
    title: title.map((x) => x.w).join(' '), titleText: span(src, title),
    topic, author, authorText, strong,
  }];
  if (!author) {
    for (let k = Math.max(1, title.length - 4); k < title.length; k += 1) {
      if (!AUTHOR_GLUE.test(title[k].w)) continue;
      const first = title[k].w.startsWith('لل') ? 'ال' + title[k].w.slice(2) : 'ا' + title[k].w.slice(2);
      const by = title.slice(k);
      out.push({
        title: title.slice(0, k).map((x) => x.w).join(' '), titleText: span(src, title.slice(0, k)),
        topic, author: [first, ...by.slice(1).map((x) => x.w)].join(' '),
        authorText: ((t) => (/^لل/u.test(t) ? 'ال' + t.slice(2) : t.replace(/^لـ?/u, '')))(span(src, by)), strong,
      });
      break;
    }
  }
  return out;
}

function splitsOf(src, rest, author, authorText) {
  const out = [];
  for (let i = 1; i < rest.length; i += 1) {
    const mk = MARKERS.find((m) => i + m.length < rest.length && m.every((w, j) => rest[i + j].w === w));
    if (!mk) continue;
    const topic = span(src, topicWords(src, rest.slice(i + mk.length)));
    out.push(...readings(src, rest.slice(0, i), topic, author, authorText, mk.length > 1 || mk[0] !== 'في'));
    i += mk.length - 1;   // a marker's own words are not markers too
  }
  out.push(...readings(src, rest, '', author, authorText, false));
  return out;
}

const PAGE_RE = /(?:^| )(?:رقم )?(?:صفحه|الصفحه|صفحات|الصفحات|ص) ?(?<page>\d+)(?= |$)/d;
const PAGE_CUE_RE = /(?:^| )(?:نص|النص|بنص|انقل|انقلي|انسخ|اقتبس|اقرا|اكتب|هات|اعطني|اعطيني|اعرض|ماذا|ما|اريد|ابي|ابغي)(?= |$)/;
const VOLUME_WORDS = new Set(['الجزء', 'جزء', 'الجز', 'المجلد', 'مجلد', 'ج']);
const PAGE_STOP = new Set(['صفحه', 'الصفحه', 'صفحات', 'الصفحات', 'ص', 'رقم', ...VOLUME_WORDS]);

function detectPage(parsed) {
  const { src, words, joined, starts } = parsed;
  const pm = PAGE_RE.exec(joined);
  if (!pm || !PAGE_CUE_RE.test(joined)) return null;
  const kitab = /(?:^| )(?:كتابه|كتاب|الكتاب) (?<rest>.+)$/d.exec(joined);
  let from;
  if (kitab) from = wordIndexAt(starts, kitab.indices.groups.rest[0]);
  else {
    // «نص صفحة ٥٠ من الجزء الثاني من مجموع الفتاوى»: skip «من الجزء الثاني», then the title.
    from = wordIndexAt(starts, pm.indices.groups.page[1]);
    for (let moved = true; moved && from < words.length;) {
      moved = false;
      if (words[from].w === 'من' || words[from].w === 'في') { from += 1; moved = true; }
      if (from < words.length && VOLUME_WORDS.has(words[from].w)) { from += 2; moved = true; }
    }
  }
  let to = from;
  while (to < words.length && !PAGE_STOP.has(words[to].w) && !/^\d+$/.test(words[to].w)) to += 1;
  const candidates = readings(src, words.slice(from, to), '', '', '', true);
  if (!candidates.length) return null;
  return { kind: 'page', shape: 'page', explicitBook: true, candidates };
}

/**
 * The reader's last message -> a request for a book's TEXT, or null.
 *   { kind: 'quote'|'page', shape, explicitBook,
 *     candidates: [{ title, titleText, topic, author, authorText, strong }] }
 * `title`/`author` are folded (for the catalogue); `titleText`/`topic`/`authorText` are the
 * reader's own characters. Lexical only: whether the title is a book is decided by planQuote().
 */
export function detectQuoteRequest(text) {
  const parsed = wordsOf(text);
  if (!parsed.words.length || parsed.src.length > 1200) return null;
  const page = detectPage(parsed);
  if (page) return page;
  for (const shape of SHAPES) {
    if (shape.cue && !TEXT_CUE.test(parsed.joined)) continue;
    const m = shape.re.exec(parsed.joined);
    if (!m) continue;
    const g = m.indices.groups;
    const rest = parsed.words.slice(wordIndexAt(parsed.starts, g.rest[0]));
    // The author group is already folded words (the match runs on the folded text).
    const author = m.groups.author ? authorKey(m.groups.author).join(' ') : '';
    const authorText = g.author
      ? span(parsed.src, parsed.words.slice(wordIndexAt(parsed.starts, g.author[0]),
        wordIndexAt(parsed.starts, g.author[1] + 1)))
      : '';
    const candidates = splitsOf(parsed.src, rest, author, authorText);
    // «من كتاب الله …» / «من القرآن …»: the reader named the Qur'an, not a book on a shelf.
    if (!candidates.length
      || candidates.some((c) => NOT_A_BOOK.has(c.title) || NOT_A_BOOK_FIRST.has(c.title.split(' ')[0]))) return null;
    return { kind: 'quote', shape: shape.name, explicitBook: !!g.kitab, candidates };
  }
  return null;
}

// ── ب٥ (order B, LIB_NAV_V1) · THE AUTHOR GLUED WITH A PLAIN «ل», SPLIT BY THE INDEX ─────────────
//
// «انقل لي من كتاب تفسير مجاهد لمجاهد بن جبر …»: `readings` above splits only «لل/لا» («لابن قدامة»,
// «للنووي»), so a plain «ل» + a name stayed inside the title, and the reader was told there is no book
// «تفسير مجاهد لمجاهد بن جبر» and asked for its author. MEASURED on c00e8f5: 1,939 of 3,074 books whose
// author a reader glues this way answered «ليس عندي» (09-order-b/b5b6/measure/j-author-glue-reach.out.txt).
//
// THE OWNER'S RULE OF 25 SEPTEMBER, LETTER FOR LETTER: «والفصلُ بالفهرسِ لا باللفظ: لا يُفصَلُ إلّا إذا
// طابقَ ما قبلَ اللامِ عنوانًا وما بعدَها مؤلّفَه». So the split is made only when the words before the
// «ل» are a title in the index (an exact or a prefix match) AND the words after it are in THAT book's
// author field. The author field and not the title's words: measured, a name found only among a title's
// words («ط ابن الجوزي» is a publisher) points at somebody else's book. A title that merely has a word
// beginning with «ل» («لغات القبائل الواردة في القرآن الكريم», «مختصر لسان العرب») is never split this way.
// Nothing here is read with the switch off, and the detector (which takes no switch) is untouched.
function authorFieldCarries(field, words) {
  const have = new Set();
  for (const w of foldArabic(field).split(/[\s،,]+/u)) {
    if (w) { have.add(nameWord(w)); have.add(stripAl(w)); }
  }
  return words.length > 0 && words.every((w) => have.has(nameWord(w)) || have.has(stripAl(w)));
}

function indexGlueReadings(ask) {
  const out = [];
  for (const c of ask.candidates) {
    if (c.author) continue;
    const words = String(c.title).split(' ').filter(Boolean);
    const texts = String(c.titleText).trim().split(/\s+/u);
    if (texts.length !== words.length) continue;
    // The same window as `readings`: the last four words, never the first.
    for (let k = Math.max(1, words.length - 4); k < words.length; k += 1) {
      if (!/^ل[^لا]/u.test(words[k]) || words[k].length < 3) continue;
      const key = authorKey([words[k].slice(1), ...words.slice(k + 1)].join(' '));
      const found = resolveBook(words.slice(0, k).join(' '), '');
      if (found.tier < 2 || !found.books.some((b) => authorFieldCarries(b.author, key))) continue;
      out.push({
        ...c,
        title: words.slice(0, k).join(' '), titleText: texts.slice(0, k).join(' '),
        author: key.join(' '), authorText: [texts[k].replace(/^لـ?/u, ''), ...texts.slice(k + 1)].join(' '),
      });
      break;
    }
  }
  return out;
}

// ── DECIDING ────────────────────────────────────────────────────────────────────
// One WORK may sit on the shelf as two editions («… ت الفحل» / «… ط الرسالة», same author): the
// edition note is dropped from the key, and all the work's ids go into the one call.
const workTitle = (title) => normalizeTitle(title).replace(/ (?:ت|ط|تحقيق|طبعه) .*$/, '');

function groupWorks(books) {
  const groups = new Map();
  for (const b of books) {
    const key = workTitle(b.title) + '|' + foldArabic(b.author);
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(b);
  }
  return [...groups.values()];
}

/**
 * detectQuoteRequest() output -> what to answer, or null when it is not ours after all.
 *   { outcome: 'search'|'page'|'need_topic'|'no_book'|'ask_which'|'blocked',
 *     books, topic, titleText, authorText }
 */
export function planQuote(ask, { form = false } = {}) {
  if (!ask || !Array.isArray(ask.candidates) || !ask.candidates.length) return null;
  let best = null;
  // ب٥ — with the switch on, the author a reader glued to the title with a plain «ل» is read too, but
  // only where the index itself says so (indexGlueReadings, below).
  const candidates = form ? [...ask.candidates, ...indexGlueReadings(ask)] : ask.candidates;
  for (const c of candidates) {
    const r = resolveBook(c.title, c.author);
    const score = [r.tier, c.topic ? 1 : 0, c.title.split(' ').length];
    if (!best || score[0] > best.score[0]
      || (score[0] === best.score[0] && (score[1] > best.score[1]
        || (score[1] === best.score[1] && score[2] > best.score[2])))) {
      best = { c, r, score };
    }
  }
  const { c, r } = best;
  // Q6: a shape without «كتاب» is ours only on a strong match that carries a topic.
  if (!ask.explicitBook && (r.tier < 2 || !c.topic)) return null;
  const open = r.books.filter((b) => !b.blocked);
  const works = r.authorScope ? (open.length ? [open] : []) : groupWorks(open);
  if (ask.kind === 'page') {
    if (r.books.length && !open.length) return { outcome: 'blocked', books: r.books, topic: '', titleText: c.titleText, authorText: '' };
    return { outcome: 'page', books: works.length === 1 ? works[0] : [], topic: '', titleText: c.titleText, authorText: '' };
  }
  if (!r.books.length) {
    // The title to echo: the one before a strong marker («ما جاء في»، «عن»), since a bare «في»
    // may sit inside a title («الغواصين في البحار»).
    // م٤-د — with the switch on, the reading that names the author is the one echoed («فقه الزكاة» by
    // «القرضاوي», not the title «فقه الزكاة للقرضاوي» and then a request for his name).
    const said = (form && ask.candidates.find((x) => x.strong && x.author))
      || ask.candidates.find((x) => x.strong) || ask.candidates[0];
    return { outcome: 'no_book', books: [], topic: c.topic, titleText: said.titleText, authorText: said.authorText };
  }
  if (!open.length) return { outcome: 'blocked', books: r.books, topic: c.topic, titleText: c.titleText, authorText: '' };
  if (works.length > 1) return { outcome: 'ask_which', books: open, topic: c.topic, titleText: c.titleText, authorText: '' };
  if (!c.topic) return { outcome: 'need_topic', books: works[0], topic: '', titleText: c.titleText, authorText: '' };
  return { outcome: 'search', books: works[0], topic: c.topic, titleText: c.titleText, authorText: '' };
}

// When a topic comes back refused (too common: the service estimates postings BEFORE the book
// filter) or empty, it is asked once more with its two or three rarest-looking words.
const COMMON_WORDS = new Set(['صلاه', 'له', 'لله', 'حكم', 'احكام', 'باب', 'فصل', 'مساله', 'مسائل', 'نبي',
  'رسول', 'صلي', 'عليه', 'وسلم', 'تعالي', 'وجل', 'رضي', 'عنه', 'عنها', 'يوم', 'ناس', 'قول', 'قال', 'كلام',
  'بعد', 'قبل', 'عند', 'غير', 'بين', 'كان', 'يجوز', 'جواز', 'ذلك', 'هذا', 'هذه', 'التي', 'الذي', 'اذا',
  'كما', 'علي', 'الي', 'فيه', 'فيها', 'منه', 'منها', 'كيف', 'ماذا', 'لماذا', 'وهل']);

export function narrowQuery(topic) {
  const words = String(topic || '').split(/\s+/).filter(Boolean);
  const scored = words.map((w, i) => ({ w, i, f: stripAl(foldArabic(w)) }))
    .filter((x) => x.f.length >= 3 && !x.f.includes(' ') && !COMMON_WORDS.has(x.f));
  if (!scored.length) return '';
  return scored.slice().sort((a, b) => b.f.length - a.f.length || a.i - b.i).slice(0, 3)
    .sort((a, b) => a.i - b.i).map((x) => x.w).join(' ');
}

// ── COMPOSING ───────────────────────────────────────────────────────────────────
const posInt = (v) => (Number.isInteger(v) && v > 0 ? v : null);

/** The card line. A page only where one can be looked up (Q8). */
export function quoteCard(atom, catalogAuto = false) {
  const parts = [`${BOOK_MARK} «${String(atom.book_title || '').trim()}»`];
  const author = String(atom.author || '').trim();
  if (author) parts.push(author);
  const start = posInt(atom.page_start);
  const printed = atom.page_citable === true && atom.numbering !== 'auto' && !catalogAuto && start !== null;
  if (printed) {
    const vol = posInt(atom.volume);
    const end = posInt(atom.page_end);
    if (vol !== null) parts.push(`ج${vol}`);
    parts.push(end !== null && end > start ? `ص${start}–${end}` : `ص${start}`);
  } else {
    const path = Array.isArray(atom.heading_path) ? atom.heading_path : [];
    let heading = String(path.length ? path[path.length - 1] : '').trim().replace(/^[-–—\s]+/u, '').trim();
    if (heading.length > HEADING_MAX) {
      const cut = heading.lastIndexOf(' ', HEADING_MAX);
      heading = heading.slice(0, cut > 0 ? cut : HEADING_MAX) + '…';
    }
    if (heading) parts.push(heading);
  }
  return parts.join(SEP);
}

const STOP_WORDS = new Set(['في', 'من', 'عن', 'علي', 'الي', 'ما', 'هو', 'هي', 'او', 'ثم', 'مع', 'كل', 'ان', 'لا']);

/** The modern scope: one paragraph, best topic overlap (ties: longer), cut before MODERN_QUOTE_MAX (Q9). */
export function modernParagraph(text, topic, truncated = false) {
  const paragraphs = String(text || '').split('\n').map((p) => p.trim()).filter(Boolean);
  if (!paragraphs.length) return '';
  const stems = [...new Set(foldArabic(topic).split(' ').filter((w) => w && !STOP_WORDS.has(w)).map(stripAl))]
    .filter((w) => w.length >= 2);
  let pick = 0;
  let bestScore = 0;
  paragraphs.forEach((p, i) => {
    const f = foldArabic(p);
    const score = stems.filter((w) => f.includes(w)).length;
    // Ties go to the LONGER paragraph: a Q&A atom's heading line («حكم …») and its «السؤال» line
    // carry the topic word as surely as the answer does, and quoting the heading alone quotes nothing.
    if (score > bestScore || (score > 0 && score === bestScore && p.length > paragraphs[pick].length)) {
      bestScore = score; pick = i;
    }
  });
  const p = paragraphs[pick];
  if (p.length > MODERN_QUOTE_MAX) {
    let end = -1;
    for (let i = 0; i < MODERN_QUOTE_MAX; i += 1) if ('.!?؟'.includes(p[i])) end = i + 1;
    if (end <= 0) {
      const sp = p.lastIndexOf(' ', MODERN_QUOTE_MAX);
      end = sp > 0 ? sp : MODERN_QUOTE_MAX;
    }
    return p.slice(0, end).trimEnd() + CUT_MARK;
  }
  return truncated && pick === paragraphs.length - 1 ? p + CUT_MARK : p;
}

/** The quoted characters for one class: whole atom (turath, fatwa) or one paragraph (modern). */
export function quotedText(atom, cls, topic = '') {
  const text = String(atom.text || '').replace(/\r\n?/g, '\n').trim();
  if (cls === 'modern') return modernParagraph(text, topic, atom.truncated === true);
  return atom.truncated === true ? text + CUT_MARK : text;
}

export function blockquote(text) {
  return String(text).split('\n').map((line) => (line ? `> ${line}` : '>')).join('\n');
}

/** Card line + blank line + the verbatim text as a markdown blockquote. */
export function composeQuoteReply(atom, cls, { catalogAuto = false, topic = '' } = {}) {
  return quoteCard(atom, catalogAuto) + '\n\n' + blockquote(quotedText(atom, cls, topic));
}

// ── THE REFUSALS AND QUESTIONS ─────────────────────────────────────────────────
// None names the machinery, none carries a page number, none claims a search it did not get.
/** A reader's words, echoed back as letters and spaces only (no digits, no markup), ≤ 80 chars. */
export function echo(value) {
  let s = String(value == null ? '' : value)
    .replace(/[^ء-غـ-ْٰA-Za-z ]+/g, ' ')
    .replace(/\s+/g, ' ').trim();
  if (s.length > 80) s = s.slice(0, s.lastIndexOf(' ', 80) > 0 ? s.lastIndexOf(' ', 80) : 80);
  return s;
}

const byAuthor = (author) => (author ? ` لـ${author}` : '');
// م٤-د — the same clause, written as Arabic writes it, and only for a name that is Arabic letters.
const byAuthorForm = (author) => (author && /[\u0621-\u064A]/u.test(author) ? ' ' + withLam(author) : '');

export function noBookReply(titleText, authorText = '', { form = false } = {}) {
  const t = echo(titleText);
  const a = echo(authorText);
  if (form) {
    // م٤-د — and the reader who named the author is not asked for him again.
    return (t ? `ليس عندي كتاب باسم «${t}»${byAuthorForm(a)}.` : 'ليس عندي كتاب بهذا الاسم.')
      + (a ? ' إن كان للكتاب اسم آخر يعرف به فاذكره لي.' : ' إن كان للكتاب اسم آخر يعرف به، أو كان عندك اسم مؤلفه، فاذكره لي.');
  }
  return (t ? `ليس عندي كتاب باسم «${t}»${byAuthor(a)}.` : 'ليس عندي كتاب بهذا الاسم.')
    + ' إن كان للكتاب اسم آخر يعرف به، أو كان عندك اسم مؤلفه، فاذكره لي.';
}

export function askWhichReply(books, { form = false } = {}) {
  const by = form ? byAuthorForm : byAuthor;
  const list = books.slice(0, ASK_LIST_MAX).map((b) => `- «${b.title}»${by(b.author)}`);
  let out = 'عندي أكثر من كتاب بهذا الاسم، فأيها تقصد؟\n\n' + list.join('\n');
  if (books.length > ASK_LIST_MAX) out += '\n\nوعندي غيرها بالاسم نفسه؛ فإن لم يكن ما تريده بينها فاذكر لي مؤلفه.';
  return out;
}

export function blockedReply(book) {
  return `لا أنقل من كتاب «${book.title}».`;
}

export function pageReply(book) {
  const t = book && !/[0-9٠-٩۰-۹]/.test(book.title) ? book.title : '';
  if (t) {
    return `لا أستطيع أن أنقل لك صفحة بعينها برقمها من «${t}». لكن اذكر لي المسألة التي تريدها منه، `
      + `وأنقل لك نص ما جاء فيها بحروفه مع موضعه من الكتاب؛ كأن تقول: «انقل لي من كتاب ${t} ما جاء في كذا».`;
  }
  return 'لا أستطيع أن أنقل لك صفحة بعينها برقمها. لكن اذكر لي اسم الكتاب والمسألة التي تريدها منه، '
    + 'وأنقل لك نص ما جاء فيها بحروفه مع موضعه من الكتاب؛ كأن تقول: «انقل لي من كتاب … ما جاء في …».';
}

export function needTopicReply(book) {
  return `اذكر لي المسألة التي تريد نصها من «${book.title}»، وأنقل لك ما جاء فيها بحروفه؛ `
    + `كأن تقول: «انقل لي من كتاب ${book.title} ما جاء في كذا».`;
}

export function noHitReply(book, topic) {
  const t = echo(topic);
  return `لم أجد في «${book.title}» شيئا عن ` + (t ? `«${t}».` : 'هذه المسألة.')
    + ' جرب أن تذكر المسألة بلفظ آخر كما قد ترد في الكتاب.';
}

export function tooBroadReply(book, topic) {
  const t = echo(topic);
  return (t ? `«${t}» باب واسع في «${book.title}».` : `هذه المسألة واسعة في «${book.title}».`)
    + ' اذكر لي مسألة أدق منه، وأنقل لك نص ما جاء فيها.';
}

export function unavailableReply(book) {
  return `تعذر علي الآن أن أنقل لك من «${book.title}». أعد السؤال بعد قليل.`;
}

// ── THE LIBRARY CALL ────────────────────────────────────────────────────────────
// A tee around the fetch lib/lib-service.js uses: the door still validates origin, redirect,
// content type and size; this only keeps the body it already read, so the quotation can be taken
// from the raw atom (heading_path, numbering, text) and not from the row's cleaned passage (Q4).
function teeFetch(base, sink) {
  return async (url, init) => {
    const response = await base(url, init);
    if (!response || !response.ok || typeof response.text !== 'function') return response;
    const body = await response.text();
    sink.body = body;
    return {
      ok: response.ok,
      status: response.status,
      url: response.url,
      redirected: response.redirected,
      headers: response.headers,
      text: async () => body,
      json: async () => JSON.parse(body),
    };
  };
}

async function searchBook(query, ids, deps) {
  const sink = { body: null };
  const ctx = {
    table: deps.createEvidenceTable(),
    spend: [],
    degraded: [],
    libFlagValue: deps.libFlagValue,
    libToken: deps.libToken,
    signal: deps.signal,
    fetchImpl: teeFetch(deps.fetchImpl || globalThis.fetch, sink),
    bookIds: ids,
    resultCap: Number.isInteger(deps.resultCap) && deps.resultCap > 0 ? deps.resultCap : QUOTE_ROWS,
    maxCharsPerHit: QUOTE_MAX_CHARS,
  };
  let out = null;
  try { out = await deps.runTool('search_library', { query }, ctx); } catch { out = null; }
  const failed = !out || out.calls === 0 || ctx.degraded.some((d) => String(d).startsWith('library:'));
  let payload = null;
  try { payload = sink.body ? JSON.parse(sink.body) : null; } catch { payload = null; }
  return {
    failed,
    rows: !failed && Array.isArray(out.added) ? out.added : [],
    refused: !!(payload && payload.refused === true),
    hits: payload && Array.isArray(payload.hits) ? payload.hits : [],
  };
}

/**
 * م٥ (LIB_NAV_V1) — «البحثُ داخلَ الكتاب» in the library section: this same search, through the same one
 * door (runTool → search_library), narrowed to ONE book and asking `rows` of it. Additive: the quote
 * path passes no resultCap, so its own call is byte-identical. deps as answerQuoteRequest's.
 */
export function searchInBook(query, bookId, deps, rows = QUOTE_ROWS) {
  return searchBook(query, [bookId], { ...deps, resultCap: rows });
}

/**
 * The whole turn, minus the writing. Returns { outcome, text } or null (not ours: the request
 * goes on to the ordinary path untouched).
 *   deps: { runTool, createEvidenceTable, libFlagValue, libToken, signal?, fetchImpl? }
 */
export async function answerQuoteRequest(ask, deps = {}) {
  // م٤-د — `deps.form` is the navigation switch, handed down by api/ask.js.
  const form = deps.form === true;
  const plan = planQuote(ask, { form });
  if (!plan) return null;
  const book = plan.books[0];
  switch (plan.outcome) {
    case 'no_book': return { outcome: 'no_book', text: noBookReply(plan.titleText, plan.authorText, { form }) };
    case 'blocked': return { outcome: 'blocked', text: blockedReply(book) };
    case 'ask_which': return { outcome: 'ask_which', text: askWhichReply(plan.books, { form }) };
    case 'page': return { outcome: 'page_request', text: pageReply(book || null) };
    case 'need_topic': return { outcome: 'need_topic', text: needTopicReply(book) };
    default: break;
  }
  if (typeof deps.runTool !== 'function' || typeof deps.createEvidenceTable !== 'function') return null;
  const ids = plan.books.map((b) => b.id);
  let got = await searchBook(plan.topic, ids, deps);
  if (got.failed) return { outcome: 'unavailable', text: unavailableReply(book) };
  if (!got.rows.length) {
    const narrow = narrowQuery(plan.topic);
    if (narrow && foldArabic(narrow) !== foldArabic(plan.topic)) {
      got = await searchBook(narrow, ids, deps);
      if (got.failed) return { outcome: 'unavailable', text: unavailableReply(book) };
    }
  }
  if (!got.rows.length) {
    return got.refused
      ? { outcome: 'too_broad', text: tooBroadReply(book, plan.topic) }
      : { outcome: 'no_hit', text: noHitReply(book, plan.topic) };
  }
  for (const row of got.rows) {
    const atom = got.hits.find((h) => h && `lib:${h.atom_id}` === row.recordId && ids.includes(h.subject_id));
    if (!atom || typeof atom.text !== 'string' || !atom.text.trim()) continue;
    // The block list is the catalogue's, and the service does not enforce it: checked again on the
    // atom that came back, not only on the ids that were asked for.
    const owner = catalogBook(atom.subject_id);
    if (!owner || owner.blocked) continue;
    return {
      outcome: 'quoted',
      text: composeQuoteReply(atom, owner.cls, { catalogAuto: owner.auto, topic: plan.topic }),
      // م٤-ب (LIB_NAV_V1) — where this quotation stopped, for «كمّل» (lib/quote-cursor.js). Additive: the
      // text is what it was; api/ask.js appends the marker only with the switch on.
      cursor: quoteCursorOf(atom),
      // م٤-ج — the atom this reply quotes, for the seal on a «ثمّ لخّصه» turn. Additive.
      page: { title: String(atom.book_title || owner.title || ''), passage: String(atom.text || '') },
    };
  }
  return { outcome: 'unavailable', text: unavailableReply(book) };
}

/**
 * م٤-ب — the cursor of one quoted atom. A turath or fatwa atom the service cut at its ceiling
 * (`truncated`) also says where it was cut and on which printed page it starts, so «كمّل» can give
 * the rest of THAT atom before moving on; an atom without print pages cannot be re-read by page, and
 * «كمّل» then moves to the next one.
 */
function quoteCursorOf(atom) {
  const cursor = { bid: String(atom.subject_id || ''), at: String(atom.atom_id || '') };
  const printed = atom.page_citable === true && atom.numbering === 'print' && Number.isInteger(atom.page_start);
  if (atom.truncated === true && printed && typeof atom.text === 'string' && atom.text.length > 0) {
    cursor.from = atom.text.length;
    cursor.v = Number.isInteger(atom.volume) ? atom.volume : 0;
    cursor.p = atom.page_start;
  }
  return cursor;
}

/**
 * The writer (Q1): the two frames sendSynthesizedText writes -- one text delta and message_stop
 * on an HTTP 200 event-stream -- without the finalizer, whose seal refuses a classical book's own
 * «روى فلان». Called only before api/ask.js commits its stream, on the raw response.
 */
export function writeQuoteReply(res, text) {
  res.status(200);
  res.setHeader('Content-Type', 'text/event-stream; charset=utf-8');
  res.setHeader('Cache-Control', 'no-cache, no-transform');
  res.setHeader('X-Accel-Buffering', 'no');
  res.flushHeaders?.();
  const frame = { type: 'content_block_delta', index: 0, delta: { type: 'text_delta', text: String(text || '') } };
  res.write(`data: ${JSON.stringify(frame)}\n\n`);
  res.write(`data: ${JSON.stringify({ type: 'message_stop' })}\n\n`);
  return res.end();
}
